dataset:
  name: FashionMNIST

architecture:
  backbone: MLPconvs

hyperparams:
  train:
    batch_size: 128
    epochs: 101
    lr: 0.0001
    loss_pen_factor: 10
    logging_pen: 0
    logging: 5
    step_scheduler: 5
    samples: 3
  architecture:
    backbone_dense_nodes: [4096,4096]
    pen_nodes: 128
