dataset:
  name: MNIST

architecture:
  backbone: MLPvanilla

hyperparams:
  train:
    batch_size: 128
    epochs: 2
    lr: 0.0001
    loss_pen_factor: 10
    logging_pen: 0
    logging: 5
    step_scheduler: 5
    samples: 2
  architecture:
    backbone_dense_nodes: [1024,1024]
    pen_nodes: 64
