dataset:
  name: MNIST

architecture:
  backbone: MLPvanilla
  
  hypers:
    backbone_dense_nodes: [2048, 2048]
    dropout: 0.5
    dense_bn: False
    conv_bn: True
    pen_nodes: 64
    activation: ReLU

training:
  hypers:
    batch_size: 64
    epochs: 3
    lr: 0.01
    loss_pen_factor: 10
    loss_pen_funct: mse
    logging_pen: 0
    logging: 1
    step_scheduler: 5
    samples: 1
    optimizer: Adam

grid_search:
  patience: 5
  hypers:
    lr: [0.001, 0.01]
    loss_pen_factor: [1, 10]
    gamma: [0.99,0.9]