dataset:
  name: CIFAR10

architecture:
  backbone: VGG13
  backbone_model: 11
  hypers:
    backbone_dense_nodes: [2048]
    dropout: 0.5
    dense_bn: False
    conv_bn: True
    pen_nodes: 64
    activation: ReLU

training:
  hypers:
    batch_size: 64
    epochs: 4
    lr: 0.01
    loss_pen_factor: 10
    loss_pen_funct: mse
    logging_pen: 0
    logging: 1
    step_scheduler: 5
    gamma: 0.9
    optimizer: SGD
